version: "3"
services:
  db:
    image: mysql:8.0.26
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    container_name: team2-back
    environment:
      - MYSQL_ROOT_PASSWORD=team2
      - MYSQL_DATABASE=team2
      - TZ=Asia/Seoul
    ports:
      - "3311:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: team2-redis
    ports:
      - "6380:6379"
    restart: always