package org.example.backend.seeder;

import org.example.backend.entity.Skill;
import org.example.backend.entity.SkillCategory;
import org.example.backend.repository.SkillCategoryRepository;
import org.example.backend.repository.SkillRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;

@Component
public class SkillSeeder implements CommandLineRunner {

    private final SkillCategoryRepository skillCategoryRepository;
    private final SkillRepository skillRepository;

    public SkillSeeder(SkillCategoryRepository skillCategoryRepository,
                       SkillRepository skillRepository) {
        this.skillCategoryRepository = skillCategoryRepository;
        this.skillRepository = skillRepository;
    }

    @Override
    public void run(String... args) throws Exception {
        if (skillCategoryRepository.count() > 0) {
            return; // 이미 데이터 존재 시 시딩 방지
        }

        // 1. 디자인
        SkillCategory design = new SkillCategory("디자인");
        List<String> designSkills = Arrays.asList(
                "Adobe Photoshop",
                "Adobe Illustrator",
                "Adobe Creative Suite",
                "Adobe Dreamweaver",
                "Adobe Flash",
                "Adobe XD",
                "Indesign",
                "MicroSoft PowerPoint",
                "Paint tool sai",
                "sketch up",
                "Corel Painter",
                "Sketch3",
                "Sketchapp",
                "Zeplin",
                "HTML & CSS",
                "Keyshot",
                "3D MAX",
                "Rhino3D",
                "CATIA",
                "3D CAD",
                "PRO-E",
                "Fusion360",
                "MAYA",
                "Zbrush",
                "Cinema4d",
                "Redshift",
                "Arnold",
                "Substance Painter",
                "CAD",
                "v-ray",
                "Figma",
                "after effect",
                "auto cad",
                "blender",
                "lumion",
                "Live2D Cubism",
                "Vtube Studio",
                "Procreate",
                "Unity",
                "Unreal Engine",
                "Substance painter",
                "Inventor",
                "Spark AR",
                "QUARKXPRESS",
                "인테리어 시공",
                "간판 시공",
                "ProtoPie",
                "SolidWorks",
                "Enscape",
                "Adobe Substance 3D",
                "Adobe Lightroom"
        );
        saveSkills(design, designSkills);

        // 2. 마케팅
        SkillCategory marketing = new SkillCategory("마케팅");
        List<String> marketingSkills = Arrays.asList(
                "인스타그램 관리",
                "키워드/검색 광고",
                "블로그 관리",
                "카페 관리",
                "검색최적화/SEO",
                "쇼핑몰 운영 대행",
                "해외 언론홍보",
                "언론 홍보",
                "포털질문/답변",
                "블로그 체험단",
                "인스타그램 체험단",
                "유튜브 체험단",
                "유튜브 관리",
                "B모임 관리",
                "메신저 채널 관리",
                "앱 마케팅",
                "디스플레이/영상/배너",
                "SNS 광고",
                "버스/지하철/택시 광고",
                "전광판/키오스크 광고",
                "신문/잡지 광고",
                "TV/라디오 광고",
                "개인 인플루언서",
                "블로그 포스팅",
                "카페 바이럴",
                "SNS 포스팅",
                "종합광고대행",
                "쇼핑몰 활성화",
                "쇼핑 태그 설치",
                "마케팅 패키지",
                "CPA 마케팅",
                "라이브커머스",
                "메시지 마케팅",
                "지도 최적화",
                "행사·이벤트",
                "마케팅 컨설팅",
                "데이터 성과 분석",
                "해외 검색",
                "해외 SNS"
        );
        saveSkills(marketing, marketingSkills);

        // 3. 번역/통역
        SkillCategory translation = new SkillCategory("번역/통역");
        List<String> translationSkills = Arrays.asList(
                "영어 번역",
                "영어 통역",
                "중국어 번역",
                "중국어 통역",
                "일본어 번역",
                "일본어 통역",
                "독일어 번역",
                "독일어 통역",
                "러시아어 번역",
                "러시아어 통역",
                "베트남어 번역",
                "베트남어 통역",
                "스페인어 번역",
                "스페인어 통역",
                "이탈리아어 번역",
                "이탈리아어 통역",
                "인도네시아어 번역",
                "인도네시아어 통역",
                "포르투갈어 번역",
                "포르투갈어 통역",
                "프랑스어 번역",
                "프랑스어 통역"
        );
        saveSkills(translation, translationSkills);

        // 4. 문서/글쓰기
        SkillCategory writing = new SkillCategory("문서/글쓰기");
        List<String> writingSkills = Arrays.asList(
                "면접 관련 경력",
                "직무 관련 경력",
                "기업 분석 관련 경력",
                "이직/진학 컨설턴트",
                "자소서 첨삭 관련 경력",
                "이력서 첨삭 관련 경력",
                "HR 관련 경력",
                "마케팅 관련 경력",
                "브랜딩 관련 경력",
                "네이밍 관련 경력",
                "홍보 관련 경력",
                "광고 대행 경력",
                "박사 학위 취득",
                "논문 첨삭 컨설턴트",
                "문서 교정 관련 경력",
                "블로그 작성 관련 경력",
                "원고작성 관련 경력",
                "작가 관련 학력·경력",
                "책 출판 관련 경력",
                "엑셀 자격증",
                "사무직 관련 경력",
                "속기사 자격증",
                "타이핑 관련 경력"
        );
        saveSkills(writing, writingSkills);

        // 5. IT·프로그래밍
        SkillCategory it = new SkillCategory("IT·프로그래밍");
        List<String> itSkills = Arrays.asList(
                "워드프레스",
                "JavaScript",
                "Java",
                "Python",
                "PHP",
                "C#",
                "Perl",
                "TypeScript",
                "React",
                "Angular",
                "ASP.NET",
                "Bootstrap",
                "Flash",
                "JSP",
                "Vue.js",
                "ASP",
                "Node.js",
                "그누보드",
                "XE",
                "모두",
                "Wix",
                "카페24",
                "고도몰",
                "메이크샵",
                "영카트",
                "식스샵",
                "Swift",
                "Android Studio",
                "C#.NET",
                "Visual Basic",
                "Lua",
                "Objective-C",
                "Go",
                "Arduino",
                "AVR",
                "Raspberry Pi",
                "STM32",
                "Erlang",
                "Verilog",
                "VHDL",
                "Excel",
                "R",
                "Matlab",
                "SPSS",
                "SAS",
                "Scala",
                "Tableau",
                "Power BI",
                "SQL",
                "Minitab",
                "Julia",
                "jQuery",
                "Unity",
                "Google SDK",
                "Unreal Engine",
                "Godot",
                "Construct",
                "GameMaker Studio",
                "Vuforia",
                "Kudan",
                "Visual Studio",
                "HTML",
                "CSS",
                "Ruby",
                "Ruby on Rails",
                "C",
                "C++",
                "Visual Basic.NET",
                "Delphi",
                "Object Pascal",
                "A#",
                "ActionScript",
                "Assembly",
                "Autohotkey",
                "AutoIt",
                "Clojure",
                "Dart",
                "Kotlin",
                "LabVIEW",
                "Liquid",
                "Rust",
                "Sass",
                "Solidity",
                "XML",
                ".NET",
                "Bulma",
                "CodeIgniter",
                "Django",
                "Electron",
                "Express.js",
                "FastAPI",
                "Flask",
                "Flutter",
                "Foundation",
                "Framework7",
                "Ionic",
                "Laminas",
                "Laravel",
                "Material-UI",
                "Materialize",
                "Next.js",
                "Qt",
                "React Native",
                "Spring",
                "Swing",
                "WPF",
                "Xamarin",
                "Angular JS",
                "Adobe Photoshop",
                "Adobe XD",
                "Axure RP",
                "Balsamiq Mockups",
                "Figma",
                "Framer",
                "Google Presentation",
                "Illustrator",
                "Invision",
                "Oven",
                "Pixate",
                "PowerMockup",
                "Microsoft Powerpoint",
                "protoNow",
                "ProtoPie",
                "Sketch",
                "UXPin",
                "Zeplin"
        );
        saveSkills(it, itSkills);

        // 6. 세무/법무/노무
        SkillCategory law = new SkillCategory("세무/법무/노무");
        List<String> lawSkills = Arrays.asList(
                "변호사 자격증",
                "세무사 자격증",
                "회계사 자격증",
                "법무사 자격증",
                "변리사 자격증",
                "노무사 자격증",
                "조직/인사/노무 전문",
                "금전/손해배상(명예훼손) 전문",
                "지식재산권(특허) 전문",
                "부동산/경매 전문",
                "증여/상속 전문",
                "회생/파산 전문",
                "빚/채무 전문",
                "이혼/가사 전문",
                "범죄/형사 전문",
                "관세사 자격증",
                "행정처분 전문",
                "보험/손해배상 전문"
        );
        saveSkills(law, lawSkills);

        // 7. 창업·사업
        SkillCategory startup = new SkillCategory("창업·사업");
        List<String> startupSkills = Arrays.asList(
                "프로젝트 컨설팅(PT, 사업계획)",
                "비즈니스 노하우",
                "현지 리서치·서베이",
                "사업계획서 컨설팅",
                "IR·PR 제안서 컨설팅",
                "피칭 컨설팅",
                "회사 소개서 작성",
                "회사 보고서 작성",
                "제품소개서",
                "R&D 컨설팅",
                "정부과제 컨설팅",
                "리포트·보고서 작성",
                "창업관련 서류작성",
                "창업 컨설팅",
                "온라인 쇼핑몰 컨설팅",
                "브랜드 컨설팅",
                "리서치 관련 자격증",
                "중국·일본 수출입 컨설팅",
                "중국·일본 현지사업 컨설팅",
                "베트남·동남아시아 수출입 컨설팅",
                "베트남·동남아시아 현지사업 컨설팅",
                "미국·북미 수출입 컨설팅",
                "미국·북미 현지사업 컨설팅",
                "러시아·유럽 수출입 컨설팅",
                "러시아·유럽 현지사업 컨설팅",
                "중동·아프리카 수출입 컨설팅",
                "중동·아프리카 현지사업 컨설팅",
                "현지 영업 지원",
                "수출입 통관",
                "마케팅·브랜딩",
                "HR관련 자격증 보유",
                "CS관련 자격증 보유",
                "HR관련팀 근무",
                "채용프로세스(면접)",
                "기업문화·조직개발",
                "평가관리",
                "직원커리어 관리",
                "어드민·정산·4대보험·근태",
                "비즈니스모델 컨설팅",
                "공모전 컨설팅",
                "상권분석",
                "화장품 제조 런칭 컨설팅",
                "카페 창업운영 컨설팅",
                "외식업 창업운영 컨설팅",
                "푸드트럭 창업운영 컨설팅",
                "에어비앤비 창업운영 컨설팅",
                "출판·인쇄물 창업운영 컨설팅",
                "패션 창업운영 컨설팅",
                "물류 진단",
                "SCM개선",
                "이노비즈인증",
                "기업부설 연구소 신청",
                "벤처인증",
                "R&D",
                "세무·회계 자격증 보유",
                "투자회사 근무",
                "자산관리 자격증 보유",
                "종합재무설계",
                "금융투자",
                "보험",
                "부동산",
                "관련 직무 근무",
                "경리업무",
                "비서업무",
                "CS·고객응대",
                "PPT 제작",
                "워드·한글 작업",
                "녹취·속기 가능",
                "비즈니스 통번역",
                "법정의무교육",
                "장애인 인식개선",
                "개인정보",
                "성희롱교육",
                "산업안전",
                "직무교육",
                "CS교육"
        );
        saveSkills(startup, startupSkills);

        // 8. 운세
        SkillCategory fortune = new SkillCategory("운세");
        List<String> fortuneSkills = Arrays.asList(
                "사주",
                "타로",
                "신점",
                "점성술",
                "손금",
                "관상",
                "꿈해몽",
                "부적",
                "굿",
                "상호작명",
                "아기이름",
                "개명",
                "한글이름",
                "이름풀이",
                "성인상담",
                "기문둔갑",
                "별자리",
                "육효",
                "자미두수"
        );
        saveSkills(fortune, fortuneSkills);

        // 9. 직무역량 레슨
        SkillCategory jobSkills = new SkillCategory("직무역량 레슨");
        List<String> jobSkillList = Arrays.asList(
                "관광통역안내사",
                "수화통역사",
                "한자한문전문지도사",
                "비즈니스회화",
                "실무회화",
                "일상회화",
                "TOEIC/speaking/writing",
                "ACT",
                "AP",
                "DELE",
                "DELF/DALF",
                "EJU",
                "FLEX",
                "GED",
                "GMAT",
                "GRE",
                "HSK",
                "IELTS",
                "JLPT",
                "JPT",
                "OPIc",
                "SAT",
                "SJPT",
                "TCF",
                "TEPS",
                "TOEFL",
                "TORFL",
                "TSC",
                "웹개발",
                "앱개발",
                "워드프레스",
                "C언어",
                "C++",
                "Java",
                "C#",
                "Delphi",
                "ASP",
                "PHP",
                "JSP",
                "ASP.NET",
                "자바스크립트",
                "HTML/CSS",
                "XML",
                "Python",
                "게임그래픽전문가",
                "게임기획전문가",
                "게임프로그래밍전문가",
                "디지털정보활용능력",
                "리눅스마스터",
                "문서실무사",
                "사무자동화산업기사",
                "워드프로세서",
                "임베디드기사",
                "전자응용기술사",
                "정보관리기술사",
                "정보기기운용기능사",
                "정보처리기능사",
                "정보처리기사",
                "정보처리산업기사",
                "컴퓨터시스템응용기술사",
                "컴퓨터운용사",
                "컴퓨터활용능력",
                "한글속기",
                "엑셀",
                "파워포인트",
                "워드/한글(문서)",
                "3D프린터개발산업기사",
                "3D프린터운용기능사",
                "웹디자인기능사",
                "전자캐드기능사",
                "컴퓨터그래픽스운용기능사",
                "포토샵",
                "일러스트",
                "인디자인",
                "3D모델링",
                "스케치",
                "UX",
                "UI",
                "데이터분석전문가",
                "데이터분석준전문가",
                "데이터아키텍처전문가",
                "SQL",
                "데이터분석",
                "머신러닝",
                "딥러닝",
                "데이터마이닝",
                "기타통계분석툴",
                "키워드광고",
                "배너광고",
                "검색최적화",
                "앱광고",
                "CRM",
                "SNS마케팅",
                "영상마케팅",
                "블로그마케팅",
                "PR/언론홍보",
                "오프라인마케팅",
                "브랜드마케팅",
                "프레젠테이션",
                "리더십",
                "스피치",
                "스토리텔링",
                "보이스트레이닝",
                "영상촬영",
                "프리미어",
                "애프터이펙트",
                "베가스",
                "파이널컷",
                "VFX",
                "콘텐츠기획",
                "유튜브운영",
                "멀티미디어콘텐츠제작전문가",
                "영사기능사",
                "영사산업기사",
                "인물사진",
                "스냅사진",
                "풍경사진",
                "제품사진",
                "사진보정",
                "디지털사진",
                "필름사진",
                "스마트폰사진",
                "사진기능사",
                "생활체육지도사",
                "퍼스널트레이닝",
                "필라테스",
                "요가",
                "수영",
                "스쿠버/프리다이빙",
                "골프",
                "댄스",
                "발레",
                "축구",
                "농구",
                "야구",
                "복싱",
                "격투기",
                "레슬링",
                "펜싱",
                "스쿼시",
                "스키/보드",
                "당구",
                "육상/마라톤",
                "체중증/감량",
                "근력증량",
                "체형교정",
                "보컬",
                "성악",
                "뮤지컬",
                "싱어송라이터",
                "랩",
                "비트박스",
                "큐베이스",
                "FL스튜디오",
                "로직스튜디오",
                "스튜디오 원",
                "프로툴",
                "에이블톤",
                "시창청음",
                "전통화성학",
                "재즈화성학",
                "작곡/편곡",
                "작사",
                "믹싱",
                "레코딩",
                "컴퓨터미디",
                "음향",
                "피아노/키보드",
                "기타",
                "베이스",
                "일랙",
                "우쿨렐레",
                "플룻",
                "클라리넷",
                "트럼펫",
                "바이올린",
                "국악기",
                "디제잉",
                "드럼",
                "가구제작기능사",
                "가구제작산업기사",
                "귀금속가곡기능장",
                "귀금속가공기능사",
                "귀금속가공산업기사",
                "금속가공기술사",
                "도자기공예기능사",
                "떡제조기능사",
                "목공예기능사",
                "석공예기능사",
                "원예기능사",
                "제과기능사",
                "제과기능장",
                "제빵기능사",
                "조주기능사",
                "주류제조관리사",
                "화훼장식기능사",
                "화훼장식기사",
                "화훼장식산업기사",
                "플라워/가드닝",
                "캘리그라피",
                "라탄",
                "목공예",
                "가죽공예",
                "천연비누",
                "디퓨저/향수",
                "도자기",
                "캔들/석고",
                "금속/악세사리",
                "자수/뜨개질/위빙",
                "포장",
                "요리/베이킹/떡",
                "커피",
                "취미미술",
                "타로카드",
                "연기",
                "마술",
                "바둑",
                "인문학/학업",
                "미용사",
                "미용장",
                "이용사",
                "이용장",
                "패션스타일리스트",
                "패션 스타일링",
                "메이크업",
                "헤어스타일링",
                "화장품/피부미용",
                "퍼스널컬러"
        );
        saveSkills(jobSkills, jobSkillList);

        // 10. 취업/입시
        SkillCategory employment = new SkillCategory("취업/입시");
        List<String> employmentSkills = Arrays.asList(
                "자소서/이력서 첨삭",
                "면접 컨설팅",
                "인적성 컨설팅",
                "자격증 컨설팅",
                "입시 컨설턴트",
                "영어 과외",
                "국어 과외",
                "수학/과학 과외",
                "논술 과외",
                "코딩 과외"
        );
        saveSkills(employment, employmentSkills);

        // 11. 투잡/노하우
        SkillCategory sideJob = new SkillCategory("투잡/노하우");
        List<String> sideJobSkills = Arrays.asList(
                "쿠팡파트너스",
                "애드센스",
                "수익형 블로그",
                "주식/재무/보험",
                "부동산/경매"
        );
        saveSkills(sideJob, sideJobSkills);

        // 12. 취미 레슨
        SkillCategory hobby = new SkillCategory("취미 레슨");
        List<String> hobbySkills = Arrays.asList(
                "헤어 스타일링 관련 자격증",
                "메이크업 관련 자격증",
                "패션/코디 관련 자격증",
                "헬스/PT 관련 자격증",
                "요가 자격증",
                "필라테스 자격증",
                "스포츠/액티비티 관련 자격증",
                "골프 자격증",
                "게임 자격증",
                "댄스 관련 자격증",
                "음악/악기 관련 자격증",
                "미술/드로잉 관련 자격증",
                "글쓰기 관련 자격증",
                "공예 관련 자격증",
                "타로/사주 관련 자격증",
                "연기 관련 자격증"
        );
        saveSkills(hobby, hobbySkills);

        // 13. 생활서비스
        SkillCategory lifestyle = new SkillCategory("생활서비스");
        List<String> lifestyleSkills = Arrays.asList(
                "가전 청소",
                "매트리스/소파/카펫 청소",
                "이사/입주/거주 청소",
                "사무실/상업공간 청소",
                "해충방역/소독",
                "곰팡이/악취 제거",
                "이사/입주청소",
                "가전 설치",
                "가전 수리",
                "도배 시공",
                "장판 시공",
                "필름 시공",
                "타일 시공",
                "조명 인테리어",
                "줄눈 시공",
                "코킹 시공",
                "기타 인테리어",
                "인테리어 컨설팅",
                "결혼식 반주 음향",
                "결혼식 사회",
                "결혼식 중계",
                "결혼식 축가",
                "웨딩 글쓰기",
                "웨딩 꽃장식",
                "웨딩 사진",
                "웨딩 스타일링",
                "웨딩 영상",
                "웨딩 인쇄/제작",
                "웨딩 플래닝",
                "돌봄",
                "반려동물",
                "여행",
                "자동차 상담"
        );
        saveSkills(lifestyle, lifestyleSkills);

        // 14. 영상/사진/음향
        SkillCategory media = new SkillCategory("영상/사진/음향");
        List<String> mediaSkills = Arrays.asList(
                "영상촬영",
                "영상편집",
                "영상보정",
                "제품사진",
                "음식사진",
                "인테리어사진",
                "행사사진",
                "인물사진",
                "프로필사진",
                "사진보정",
                "작사",
                "작곡",
                "편곡",
                "믹싱/마스터링",
                "음원편집",
                "채보/사보",
                "성우",
                "내레이션",
                "캐릭터 성우",
                "ARS 녹음",
                "모델",
                "MC",
                "배우",
                "공연",
                "Pro Tools",
                "Adobe Audition",
                "Logic Pro X",
                "Cubase",
                "Ableton Live",
                "FL studio",
                "Studio One",
                "Adobe Premiere Pro",
                "Final Cut Pro",
                "Davinci Resolve",
                "Adobe After Effects",
                "Cinema 4D",
                "EDIUS",
                "Avid Media Composer",
                "Adobe Photoshop Lightroom"
        );
        saveSkills(media, mediaSkills);

        // 15. 심리상담
        SkillCategory psychology = new SkillCategory("심리상담");
        List<String> psychologySkills = Arrays.asList(
                "MBTI 검사",
                "TCI 검사",
                "MMPI 검사",
                "SCT 검사",
                "버크만진단 검사",
                "그림 검사",
                "로르샤흐 검사",
                "부부/가족 상담",
                "연애 상담",
                "육아/아동/청소년 상담",
                "진로 상담",
                "집단 상담",
                "코칭",
                "놀이치료",
                "독서치료",
                "미술치료",
                "사진치료",
                "언어치료",
                "연극치료",
                "영화치료",
                "음악치료"
        );
        saveSkills(psychology, psychologySkills);

        // 16. 주문제작
        SkillCategory customOrder = new SkillCategory("주문제작");
        List<String> customOrderSkills = Arrays.asList(
                "인쇄",
                "간판 제작",
                "제품 제작",
                "시공/공사"
        );
        saveSkills(customOrder, customOrderSkills);
    }

    private void saveSkills(SkillCategory category, List<String> skillNames) {
        skillCategoryRepository.save(category);

        for (String skillName : skillNames) {
            Skill skill = new Skill(skillName, category);
            skillRepository.save(skill);
        }
    }
}
